let mock = [{
    id: 1,
    teacher: "Heather Fields",
    name: "BIO 100",
    days: "MWF",
    time: "9:00 - 9:50 AM",
    add: "+",
  },
  {
    id: 2,
    teacher: "John Brown",
    name: "MATH 113",
    days: "MWF",
    time: "10:00 - 10:50 AM",
    add: "+",
  },
  {
    id: 3,
    teacher: "Betty White",
    name: "CS 142",
    days: "MWF",
    time: "11:00 - 11:50 AM",
    add: "+",
  },
  {
    id: 4,
    teacher: "Dave Briggs",
    name: "REL C 200",
    days: "TTh",
    time: "2:00 - 2:50 PM",
    add: "+",
  },
  {
    id: 5,
    teacher: "Jenifer Morales",
    name: "SPAN 321",
    days: "MWF",
    time: "4:00 - 4:50 PM",
    add: "+",
  },
  {
    id: 6,
    teacher: "Bob Newman",
    name: "HLTH 313",
    days: "TTh",
    time: "12:00 - 12:50 PM",
    add: "+",
  },
  {
    id: 7,
    teacher: "Sarah Silvester",
    name: "PSYCH 111",
    days: "TTh",
    time: "8:00 - 8:50 AM",
    add: "+",
  },
  {
    id: 8,
    teacher: "Larry Jacobs",
    name: "WRTG 105",
    days: "MWF",
    time: "9:00 - 9:50 AM",
    add: "+",
  },
  {
    id: 9,
    teacher: "Hannah Johnson",
    name: "NURS 102",
    days: "MWF",
    time: "1:00 - 1:50 PM",
    add: "+",
  },
  {
    id: 10,
    teacher: "Hank Smith",
    name: "REL A 121",
    days: "MWF",
    time: "10:00 - 10:50 AM",
    add: "+",
  },
]

export default mock;
